version: '3.8'

services:
  express:
    build:
      context: ./express
    volumes:
      - "./express/app:/app"
      - "./nginx/cache:/cache"

  nginx:
    image: nginx:1.21
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/cache:/cache"
    ports:
      - "80:80"
